id: P009501
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 19:41:38.753813
source_metadata:
  id: bdr:W3CN4314
  title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་རྩ་བ།
  author: ''
  volumes:
    c409de4faedd4766881ae968e3a3dee4:
      image_group_id: I3CN8548
      title: ''
      volume_number: 1
      total_pages: 62
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
